version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "file:./data.db"
        NODE_ENV: production
        PORT: 5056
        HOSTNAME: 0.0.0.0
    ports:
      - "5056:5056"
    restart: unless-stopped