version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "file:./data.db"
        NODE_ENV: production
        PORT: 3000
        HOSTNAME: 0.0.0.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    # environment:
    #   - DATABASE_URL=file:./data.db
    #   - NODE_ENV=production
    #   - PORT=3000
    #   - HOSTNAME=0.0.0.0